In [ ]:
class LinearRegression():
    def __init__(self, rate=0.01, n=10000):
        self.rate = rate
        self.n = n
        self.coef_ = []
        self.intercept_ = None
        self.weights = None
        self.bias = None
        self.loss = []

    def __str__(self):
        return "{} ({}, {})".format(self.n, self.x, self.y)

    def fit(self, X: list, y: list):
        pass

    def predict(self, X: list):
        pass

    #Helper Functions

    def _meanSumErr(self, y, y_hat):
        err = 0
        for i in range(len(y)):
            err += (y[i] - y_hat[i])
        return err/len(y)




In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

class LinearRegression:
    def __init__(self):
        self.coeff = []
        self.intercept = 0

    def fit(self, X, y, alpha=.01, num_iterations=1000):
        '''
        fit
        '''

        if isinstance(X, pd.DataFrame) or isinstance(X, pd.Series):
            X = X.to_numpy()
        if isinstance(y, pd.DataFrame) or isinstance(y, pd.Series):
            y = y.to_numpy()

        X = np.c_[np.ones((len(X), 1)), X]

        m = len(X)
        num_features = X.shape[1]
        print('sample count:', m)
        print('feature count:', num_features)

        theta = np.zeros((num_features, 1))

        for iteration in range(num_iterations):
            y_hat = np.dot(X, theta)

            error = y_hat - y
            #Transformed X * Error
            gradv = np.dot(X.T, error)

            theta = theta - alpha * gradv / m

        self.intercept = theta[0, 0]
        self.coeff = list(theta[1,:])

    def predict(self, X):
        '''
        Predict y using the LinearRegression model on X
        '''
        return np.dot(X, self.coeff) + self.intercept

    def _get_coeff(self):
        return self.coeff

    def _get_intercept(self):
        return self.intercept

if __name__ == '__main__':
    df = pd.read_csv("bitcoin.csv")
    X = df["Open"]
    y = df["Close"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=6, test_size=0.2)

    model = LinearRegression()
    model.fit(X_train, y_train)
    yPred = model.predict((X_test))
    print(yPred)

sample count: 2512
feature count: 2


/var/folders/64/flxd5m1x7x3b4y8j154r30bh0000gn/T/ipykernel_6132/3743904552.py:36: RuntimeWarning: invalid value encountered in subtract
  theta = theta - alpha * gradv / m


ValueError: shapes (628,) and (2512,) not aligned: 628 (dim 0) != 2512 (dim 0)

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt

class LinearRegression():
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
        self.num_iterations=10000

    def fit(self,X,y):

        if isinstance(X, pd.DataFrame) or isinstance(X, pd.Series):
            X = X.to_numpy()
        if isinstance(y, pd.DataFrame) or isinstance(y, pd.Series):
            y = y.to_numpy()

        if len(y.shape) == 1:
            y = np.reshape(y, (len(y), 1))

        self.coef_, self.intercept_ = self._multi_linear_regression(X, y)

    def predict(self, testX):

        return testX * self.coef_[0] + self.intercept_

    def simple_linear_regression(self, X, y):
        n = len(X)
        alpha = 0
        beta = 0
        for i in range(self.num_iterations):
            Y_pred = alpha * X + beta
            D_alph = (-2 / n) * sum(X * (y - Y_pred))
            D_beta = (-2 / n) * sum(y - Y_pred)
            alpha = alpha - .01 * D_alph
            beta = beta - .01 * D_beta

        reg_line = 'y = {} + {}β'.format(alpha[0], np.round(beta[0], 3))
        print(reg_line)
        return alpha, beta[0]

    def _multi_linear_regression(self, X, y, alpha=0.01):

        X = np.c_[np.ones((len(X), 1)), X]

        m = len(X)
        num_features = X.shape[1]
        print('sample count:', m)
        print('feature count:', num_features)

        theta = np.zeros((num_features, 1))

        X_transpose = X.T
        for iteration in range(self.num_iterations):
            y_hat = X.dot(theta)
            print(y_hat)
            error = np.subtract(y_hat, y)
            print(error)
            #gradv = np.dot(X_transpose, error)
            gradv=X_transpose.dot(error)
            print(gradv)
            theta = theta - (alpha/m) * gradv
            print(theta)
            if iteration == 50:
                break
        return theta[1:], theta[0, 0]




if __name__ == '__main__':
    df = pd.read_csv("housing_data.csv")
    df = df.dropna()
    X = df[["housing_median_age" ,"total_rooms" ,"total_bedrooms"]]
    y = df[["median_house_value"]]
    X_train = X.iloc[:-30,:]
    y_train = y.iloc[:-30,:]
    X_test = X.iloc[-30:,:]
    y_test = y.iloc[-30:,:]

    df = pd.DataFrame({'f1':[2,4,7], 'f2':[4,5,10],'f3':[9, 4, 3], 'y':[4,8,14]})
    model = LinearRegression()
    model.fit(df[['f1', 'f2']], df[['y']])

    yPred = model.predict(df[['f3']])
    print(f"Multi: \n{yPred}")

sample count: 3
feature count: 3
[[0.]
 [0.]
 [0.]]
[[ -4.]
 [ -8.]
 [-14.]]
[[ -26.]
 [-138.]
 [-196.]]
[[0.08666667]
 [0.46      ]
 [0.65333333]]
[[3.62      ]
 [5.19333333]
 [9.84      ]]
[[-0.38      ]
 [-2.80666667]
 [-4.16      ]]
[[ -7.34666667]
 [-41.10666667]
 [-57.15333333]]
[[0.11115556]
 [0.59702222]
 [0.84384444]]
[[ 4.68057778]
 [ 6.71846667]
 [12.72875556]]
[[ 0.68057778]
 [-1.28153333]
 [-1.27124444]]
[[ -1.8722    ]
 [-12.66368889]
 [-16.3978    ]]
[[0.11739622]
 [0.63923452]
 [0.89850378]]
[[ 4.98988037]
 [ 7.16685319]
 [13.57707563]]
[[ 0.98988037]
 [-0.83314681]
 [-0.42292437]]
[[-0.26619081]
 [-4.31329711]
 [-4.4354563 ]]
[[0.11828352]
 [0.65361218]
 [0.91328863]]
[[ 5.0786624 ]
 [ 7.29917539]
 [13.82645507]]
[[ 1.0786624 ]
 [-0.70082461]
 [-0.17354493]]
[[ 0.20429287]
 [-1.86078812]
 [-0.9249227 ]]
[[0.11760255]
 [0.6598148 ]
 [0.91637171]]
[[ 5.10271898]
 [ 7.3387203 ]
 [13.90002324]]
[[ 1.10271898]
 [-0.6612797 ]
 [-0.09997676]]
[[ 0.34146253]
 [-1.13951813]
 [ 

In [ ]:
if __name__ == "__main__":

    model = LinearRegression()
    model.fit(X=None, y=None)
    model.predict(xTest=None)
